export const GET_CONTACTS = 'GET_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const FILTER_CONTACTS = 'FILTER_CONTACTS';
export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const CONTACT_ERROR = 'CONTACT_ERROR';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_PEOPLE = 'GET_PEOPLE';
export const PEOPLE_ERROR = 'PEOPLE_ERROR';
export const FILTER_PEOPLE = 'FILTER_PEOPLE';
export const CLEAR_FILTER_PEOPLE = 'CLEAR_FILTER_PEOPLE';
export const ADD_FRIEND = 'ADD_FRIEND';
export const ACCEPT_FRIEND = 'ACCEPT_FRIEND';
export const REJECT_FRIEND = 'REJECT_FRIEND';
export const FRIEND_ERROR = 'FRIEND_ERROR';
export const CLEAR_FRIEND_ERROR = 'CLEAR_FRIEND_ERROR';

export const GET_MESSAGES = 'GET_MESSAGES';
export const MESSAGES_ERROR = 'MESSAGES_ERROR';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_ERROR = 'MESSAGE_ERROR';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const CONVERSATION_ERROR = 'CONVERSATION_ERROR';
